from app import IMAGES_DIR, connection, render_template, request, session, os, time

def submit_comment():
    request_data = request.form
    comment = request_data["comment"]   # get comment from form data
    photoid = request_data["photoid"]   # get photoid from form data
    query = "insert into comment (username, photoID, commentText) VALUES (%s, %s, %s)" #timestamp is generated by db
    try:
        with connection.cursor() as cursor:
            cursor.execute(query, (session["username"], photoid, comment))
    except:
        # decided to fail silently rather than change the db schema bc we like that each user is limited in the number of
        # comments. it reduces spam for a user
        print("fail silently for duplicate entries or other db failures")
